//Stock price data as of EOD 06/26/19; initial price as of 12/31/18 

const stockData = [
    {
        ticker: 'NKE',
        name: 'Nike, Inc.',
        price: 82.55,
        exchange: 'NYSE',
        chart: '/images/NKE.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'DATA',
        name: 'Tableau Software, Inc.',
        price: 162.10,
        exchange: 'NYSE',
        chart: '/images/DATA.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'WMT',
        name: 'Walmart Inc.',
        price: 110.16,
        exchange: 'NYSE',
        chart: '/images/WMT.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'NSANY',
        name: 'Nissan Motor Co.',
        price: 14.29,
        exchange: 'Other OTC',
        chart: '/images/NSANY.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'SPOT',
        name: 'Spotify Technology',
        price: 144.79,
        exchange: 'NYSE',
        chart: '/images/SPOT.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'SFRGY',
        name: 'Salvatore Ferragamo S.p.A.',
        price: 12.00,
        exchange: 'Other OTC',
        chart: '/images/SFRGY.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'AAPL',
        name: 'Apple Inc.',
        price: 200.91,
        exchange: 'Nasdaq',
        chart: '/images/AAPL.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'TIF',
        name: 'Tiffany & Co.',
        price: 94.15,
        exchange: 'NYSE',
        chart: '/images/TIF.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'GOOGL',
        name: 'Alphabet Inc.',
        price: 1096.19,
        exchange: 'Nasdaq',
        chart: '/images/GOOGL.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'QLYS',
        name: 'Qualys, Inc.',
        price: 86.21,
        exchange: 'Nasdaq',
        chart: '/images/QLYS.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'WORK',
        name: 'Slack Technologies',
        price: 36.91,
        exchange: 'NYSE',
        chart: '/images/WORK.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'TSLA',
        name: 'Tesla, Inc.',
        price: 227.16,
        exchange: 'Nasdaq',
        chart: '/images/TSLA.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'GPS',
        name: 'The Gap, Inc.',
        price: 17.75,
        exchange: 'NYSE',
        chart: '/images/GPS.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'BERNMAD',
        name: 'Bernie Madoff Fund of Funds',
        price: 6.97,
        exchange: 'Direct to Bernie',
        chart: '/images/APRN.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'APRN',
        name: 'Blue Apron Holdings',
        price: 6.97,
        exchange: 'NYSE',
        chart: '/images/APRN.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'OJS',
        name: 'OJ Simpson Anonymous',
        price: 17.09,
        exchange: 'Direct to OJ',
        chart: '/images/VWAGY.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'VWAGY',
        name: 'Volkswagen AG',
        price: 17.09,
        exchange: 'Other OTC',
        chart: '/images/VWAGY.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'SHLDQ',
        name: 'Sears Holdings Corp.',
        price: 0.28,
        exchange: 'Other OTC',
        chart: '/images/SHLDQ.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'MCD',
        name: `McDonald's Corporation`,
        price: 206.60,
        exchange: 'NYSE',
        chart: '/images/MCD.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
    {
        ticker: 'RRGB',
        name: 'Red Robin Gourmet Burgers',
        price: 30.40,
        exchange: 'Nasdaq',
        chart: '/images/RRGB.png',
        initialPurchasePrice: 0,
        priceChange: 0,
        sharesOwned: 0,
        initialInvestment: 0,
        totalInvested: 0,
        capGain: 0,
        newShares: 0
    },
]

module.exports = {
    stockData
}